# Generated by Django 5.0.6 on 2024-06-19 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0008_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='qty_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='Admin_side.product'),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='variation_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='Admin_side.variationoption'),
        ),
    ]
