# Generated by Django 5.0.6 on 2024-06-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0009_remove_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_side.product'),
        ),
    ]
