# Generated by Django 5.0.6 on 2024-06-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0012_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconfiguration',
            name='variation_option',
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='variation_options',
            field=models.ManyToManyField(related_name='configurations', to='Admin_side.variationoption'),
        ),
    ]
