# Generated by Django 5.0.6 on 2024-06-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0013_remove_productconfiguration_variation_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_in_stock',
        ),
    ]
