# Generated by Django 5.0.6 on 2024-06-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0015_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='category',
            new_name='product',
        ),
    ]
