# Generated by Django 5.0.6 on 2024-06-29 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0019_product_created_at_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_side.shippingmethod'),
        ),
    ]
