# Generated by Django 5.0.6 on 2024-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0024_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
