# Generated by Django 5.0.6 on 2024-07-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0025_coupon_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
