# Generated by Django 5.0.6 on 2024-07-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0026_alter_coupon_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='used_count',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
