# Generated by Django 5.0.6 on 2024-07-10 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0029_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('product_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_side.productconfiguration')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_side.wishlist')),
            ],
            options={
                'unique_together': {('wishlist', 'product_configuration')},
            },
        ),
    ]
