# Generated by Django 5.0.6 on 2024-07-11 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0031_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('ADD', 'Add Funds'), ('WITHDRAW', 'Withdraw Funds'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_side.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_side.wallet')),
            ],
        ),
    ]
