# Generated by Django 5.0.6 on 2024-07-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0033_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Admin_side.category')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_side.offer')),
            ],
            options={
                'unique_together': {('category', 'offer')},
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_side.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Admin_side.product')),
            ],
            options={
                'unique_together': {('product', 'offer')},
            },
        ),
        migrations.CreateModel(
            name='SubcategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_side.offer')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Admin_side.subcategory')),
            ],
            options={
                'unique_together': {('subcategory', 'offer')},
            },
        ),
    ]
