# Generated by Django 5.0.6 on 2024-07-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0034_categoryoffer_productoffer_subcategoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
