# Generated by Django 5.0.6 on 2024-07-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0035_offer_min_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
