# Generated by Django 5.0.6 on 2024-07-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0038_alter_productoffer_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoffer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='proproduct_configurationduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Admin_side.productconfiguration'),
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
    ]
