# Generated by Django 5.0.6 on 2024-07-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0040_rename_proproduct_configurationduct_productoffer_proproduct_configurationd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='proproduct_configurationd',
            new_name='proproduct_configuration',
        ),
    ]
