# Generated by Django 5.0.6 on 2024-07-20 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0043_carouselbanner_offerbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_side.paymentstatus'),
        ),
    ]
