# Generated by Django 5.0.6 on 2024-07-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_side', '0046_alter_orderreturnstatus_status_permanentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='permanent_address_line1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='permanent_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='permanent_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='permanent_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='permanent_postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='permanent_state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
