from django.urls import path
from . import views

urlpatterns = [
    path('', views.adminLogin, name="adminLogin"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('customers/', views.customers, name='customers'),
    path('block/<int:pk>/', views.block, name='block'),
    path('unblock/<int:pk>/', views.unblock, name='unblock'),
    path('category/', views.category, name='category'),
    path('addCategory/', views.addCategory, name='addCategory'),
    path('editCategory/<pk>/', views.editCategory, name='editCategory'),
    path('editSubcategory/<pk>/', views.editSubcategory, name='editSubcategory'),
    path('blockCategory/<int:pk>/', views.blockCategory, name='blockCategory'),
    path('unblockCategory/<int:pk>/', views.unblockCategory, name='unblockCategory'),
    path('blockSubcategory/<int:pk>/', views.blockSubcategory, name='blockSubcategory'),
    path('unblockSubcategory/<int:pk>/', views.unblockSubcategory, name='unblockSubcategory'),
    path('product/', views.product, name='product'),
    path('addProduct/', views.addProduct, name='addProduct'),
    path('productAbout/<pk>', views.productAbout, name='productAbout'),
    path('variant/<pk>', views.variant, name='variant'),
    path('editvariant/<pk>', views.editvariant, name='editvariant'),
    path('productConfiguration/<pk>', views.productConfiguration, name='productConfiguration'),
    path('blockProduct/<int:pk>/', views.blockProduct, name='blockProduct'),
    path('unblockProduct/<int:pk>/', views.unblockProduct, name='unblockProduct'),
    path('get_subcategories/<int:category_id>/', views.get_subcategories, name='get_subcategories'),
    path('editProduct/<pk>/', views.editProduct, name='editProduct'),
    path('orders/', views.orders, name='orders'),
    path('addCoupon/', views.addCoupon, name='addCoupon'),
    path('coupons/', views.coupons, name='coupons'),
    path('change_order_status/<int:order_id>/', views.change_order_status, name='change_order_status'),
    path('stock_management/', views.stock_management, name='stock_management'),
    path('update_stock/', views.update_stock, name='update_stock'),
    path('toggle-coupon-status/', views.toggle_coupon_status, name='toggle_coupon_status'),
    path('createOffer/', views.create_offer, name='createOffer'),
    path('toggle-offer-status/', views.toggle_offer_status, name='toggle_offer_status'),
    path('offers/', views.offers, name='offers'),
    path('get-product-configurations/<int:product_id>/', views.get_product_configurations, name='get_product_configurations'),
    path('sales-report/', views.sales_report, name='sales_report'),
    path('export-excel/<int:report_id>/', views.export_excel, name='export_excel'),
    path('export-pdf/<int:report_id>/', views.export_pdf, name='export_pdf'),
    path('adminLogout/', views.adminLogout, name='adminLogout'),
]
